import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import PageHeader from '../components/PageHeader';
import LoadingSpinner from '../components/LoadingSpinner';
import { fetchReport } from '../services/reportService';
import { formatDate, severityTone } from '../utils/formatters';

export default function ResultPage() {
  const { reportId } = useParams();
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    const loadReport = async () => {
      try {
        const response = await fetchReport(reportId);
        setReport(response.report);
      } catch (requestError) {
        setError(requestError.message || 'Unable to load the requested report.');
      } finally {
        setLoading(false);
      }
    };

    loadReport();
  }, [reportId]);

  if (loading) {
    return <LoadingSpinner label="Loading report details..." />;
  }

  if (error) {
    return <p className="rounded-2xl bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</p>;
  }

  if (!report) {
    return null;
  }

  return (
    <div>
      <PageHeader
        eyebrow="Prediction output"
        title="NAPSI severity result"
        description="Structured prediction output returned by the Flask inference pipeline and stored in Firestore."
        actions={<Link to="/history" className="button-secondary">Back to History</Link>}
      />

      <div className="grid gap-8 lg:grid-cols-[0.95fr_1.05fr]">
        <div className="panel overflow-hidden">
          <img src={report.processed_image_url || report.image_url} alt="Processed nail scan" className="h-full min-h-[420px] w-full object-cover" />
        </div>

        <div className="space-y-6">
          <div className="panel p-6">
            <div className="flex items-start justify-between gap-4">
              <div>
                <p className="text-sm font-bold uppercase tracking-[0.2em] text-slatebrand-500">NAPSI score</p>
                <h2 className="mt-4 text-5xl font-extrabold tracking-tight text-slatebrand-900">{report.napsi_score}</h2>
                <p className="mt-3 text-sm text-slatebrand-600">Generated {formatDate(report.created_at)}</p>
              </div>
              <span className={`rounded-full px-4 py-3 text-sm font-bold ${severityTone(report.severity)}`}>
                {report.severity}
              </span>
            </div>
          </div>

          <div className="panel p-6">
            <p className="text-sm font-bold uppercase tracking-[0.2em] text-slatebrand-500">Feature breakdown</p>
            <div className="mt-5 grid gap-4 sm:grid-cols-2">
              {Object.entries(report.features || {}).map(([feature, enabled]) => (
                <div key={feature} className="rounded-3xl border border-slatebrand-100 bg-slatebrand-50 p-5">
                  <p className="text-sm font-semibold uppercase tracking-[0.18em] text-slatebrand-500">{feature}</p>
                  <p className="mt-3 text-2xl font-bold text-slatebrand-900">{enabled ? 'Detected' : 'Not detected'}</p>
                </div>
              ))}
            </div>
          </div>

          <div className="panel p-6">
            <p className="text-sm font-bold uppercase tracking-[0.2em] text-slatebrand-500">Interpretation</p>
            <p className="mt-4 text-base leading-8 text-slatebrand-700">
              This report is generated by an ensemble of three classification models (ResNet50, EfficientNetB0, and MobileNetV3Large) and stored through the Flask + Firestore pipeline.
            </p>
            
            {report.predicted_class && (
              <div className="mt-6 rounded-3xl bg-slatebrand-50 p-5">
                <p className="text-sm font-semibold uppercase tracking-[0.18em] text-slatebrand-500">Model Detection</p>
                <p className="mt-2 text-lg font-bold text-slatebrand-900">
                  Class: <span className="text-slatebrand-600">{report.predicted_class.replace(/_/g, ' ')}</span>
                </p>
                {report.confidence && (
                  <p className="mt-1 text-sm text-slatebrand-700">
                    Confidence: {(report.confidence * 100).toFixed(2)}%
                  </p>
                )}
                
                {report.model_votes && (
                  <div className="mt-4">
                    <p className="text-xs font-semibold uppercase tracking-[0.18em] text-slatebrand-500">Individual Model Votes</p>
                    <div className="mt-2 space-y-1">
                      {Object.entries(report.model_votes).map(([model, score]) => (
                        <div key={model} className="flex justify-between text-sm">
                          <span className="text-slatebrand-600">{model}:</span>
                          <span className="font-semibold text-slatebrand-900">{(score * 100).toFixed(2)}%</span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
